---
format_version: 1
pipelines:
  ci-workshop: # pipeline name
    group: ciworkshop-tasks # pipeline group
    label_template: '${ci-workshop[:8]}'
    lock_behavior: none
    materials:
      ci-workshop:
        git: 'git@github.com:minnn-tw/ci-workshop.git'
        branch: master
    stages:
      - Unit-Test:
          clean_workspace: true
          jobs:
            run-test:
              tasks:
                - exec:
                    command: ./batect
                    arguments:
                      - unitTest
