format_version: 1
pipelines:
  ci-workshop-tasks:
    group: ciworkshop-tasks
    label_template: '${ci-workshop[:8]}'
    lock_behavior: none
    materials:
      ci-workshop:
        git: 'git@github.com:minnn-tw/ci-workshop.git'
        branch: tasks
    stages:
      - Unit-Test:
          clean_workspace: true
          jobs:
            run-test:
              tasks:
                - exec:
                    command: ./batect
                    arguments:
                      - unitTest
      - Build-Image:
          approval:
            type: auto
            allow_only_on_success: true
          jobs:
            build-image:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - build
#      - Deploy-App:
#          jobs:
#            deploy-image:
#              tasks:
#                - exec:
#                    command: ./batect
#                    argument:
#                      - start-app # but doing this will jsut run in endlessly on the server/agent
