format_version: 1
pipelines:
  ci-workshop-tasks:
    group: ciworkshop-tasks
    label_template: '${ci-workshop[:8]}'
    lock_behavior: none
    materials:
      ci-workshop:
        git: 'git@github.com:minnn-tw/ci-workshop.git'
        branch: tasks
    stages:
      - Unit-Test:
          clean_workspace: true
          jobs:
            run-test:
              tasks:
                - exec:
                    command: ./batect
                    arguments:
                      - unitTest
      - Build-Image:
          jobs:
            build-image:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - build
