format_version: 9
pipelines:
  SampleApp:
    group: MyGroup
    materials:
      repository:
        git: https://github.com/wanichnun-tw/ci-workshop.git
        branch: master
    stages:
      - test:
          clean_workspace: true
          jobs:
            run-unit-test:
              tasks:
                - exec:
                    arguments:
                      - run
                      - hello-world
                    command: docker
