format_version: 9
pipelines:
  01-HelloWorld:
    group: MyGroup
    materials:
      repository:
        git: git@github.com:wanichnun-tw/ci-workshop.git
        branch: master
    stages:
      - hello:
          clean_workspace: true
          jobs:
            run-hello-world:
              tasks:
                - exec:
                    command: ./scripts/01-helloworld
  02-BuildMyApp:
    group: MyGroup
    materials:
      repository:
        git: git@github.com:wanichnun-tw/ci-workshop.git
        branch: master
    stages:
      - test:
          clean_workspace: true
          jobs:
            run-unit-test:
              tasks:
                - exec:
                    command: ./scripts/02-unit-test
      - build:
          clean_workspace: true
          jobs:
            build-the-app:
              artifacts:
                - build:
                    source: build/libs/ci-workshop.jar
                    destination: app.jar
              tasks:
                - exec:
                    command: ./scripts/03-build

